---
title: "Qual_quant_merging"
output: html_notebook
---

```{r Packages}
if (!require("descr")) {install.packages("descr"); require("descr")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")} 
if (!require("formatR")) {install.packages("formatR"); require("formatR")} 
if (!require("psych")) {install.packages("psych"); require("psych")}    
if (!require("readxl")) {install.packages("readxl"); require("readxl")}    
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")} 
```

```{r Raw datasets}
Data_round_1 <- read.csv("Raw_data/NLP Round 1 TP1 S - Raw data.csv")
Data_round_2 <- read.csv("Raw_data/NLP Round 2 TP1 S - Raw data.csv")
Data_round_3 <- read.csv("Raw_data/NLP Round 3 TP1 S - Raw data.csv")
Data_round_4 <- read.csv("Raw_data/NLP Round 4 TP1 S  - Raw Data.csv")
Data_round_5 <- read.csv("Raw_data/NLP Round 5 TP1 NS - Raw data.csv")
Data_round_6 <- read.csv("Raw_data/NLP Round 6 TP1 NS - Raw data.csv")
```

```{r Raw merging checks}
#### Get ducks in a row ####

# Look at variable discrepancies
setdiff(colnames(Data_round_1), colnames(Data_round_2))
setdiff(colnames(Data_round_2), colnames(Data_round_1))

# need to resolve discrepancies and make Data_round_1 consistent with Data_round_2, since round_2 is consistent with the others. 

Data_round_1 <- Data_round_1 %>%
  # renaming "FSCQ1" through "FSCQ10" as "FSCQ.1" through "FSCQ.10"
  rename_with(
    .fn = ~ gsub("FSCQ(\\d+)", "FSCQ.\\1", .x),
    .cols = starts_with("FSCQ")
  ) %>%
  # Renaming "RESST_1" through "RESST_21" --> Recovery.scale_1 through "Recovery.scale_21"
  rename_with(
    .fn = ~ gsub("^RESST_", "Recovery.scale_", .x),
    .cols = starts_with("RESST_")
  )

# Change other random discrepancies
Data_round_1 <- Data_round_1 %>%
  dplyr::rename(
    Sexual.orientation = Sexual.Orientation,
    Sexual.orientation_4_TEXT = Sexual.Orientation_4_TEXT,
    Discharge = Military.discharge, 
    SBQR.time_First.Click = SBQR.Time_First.Click, 
    SBQR.time_Last.Click = SBQR.Time_Last.Click,
    SBQR.time_Page.Submit = SBQR.Time_Page.Submit,
    SBQR.time_Click.Count = SBQR.Time_Click.Count, 
    SBQR.6 = Start.Date)

# rename Qs 31 through 45 as 139 through 153
# These are the verbal questions FEEDBACK. 
# Looks like round 1 were asked 2 extra questions which participants noted they weren't asked about originally. We'll exclude those from the dataframe after this
start_index <- 31
end_index <- 45
new_start_index <- 139
old_cols <- paste0("Q", start_index:end_index)
new_cols <- paste0("Q", new_start_index:(new_start_index + (end_index - start_index)))

Data_round_1 <- Data_round_1 %>%
  rename_with(
    .fn = ~ new_cols[match(.x, old_cols)],
    .cols = matches(paste0("^", paste0("Q", start_index:end_index), "$"))
  )

# Remove 2 extra feedback questions
Data_round_1 <- Data_round_1 %>%
  select(-Q46, -Q47)

# Now check discrepancies between dataframes again
setdiff(colnames(Data_round_1), colnames(Data_round_2))
setdiff(colnames(Data_round_2), colnames(Data_round_1))

setdiff(colnames(Data_round_2), colnames(Data_round_3))
setdiff(colnames(Data_round_3), colnames(Data_round_2))

setdiff(colnames(Data_round_4), colnames(Data_round_3))
setdiff(colnames(Data_round_3), colnames(Data_round_4))

setdiff(colnames(Data_round_1), colnames(Data_round_4))
setdiff(colnames(Data_round_5), colnames(Data_round_4))
```


```{r Raw quantitative merging}

##### round 2 #####
Round_1_2_merged <- merge(Data_round_1, Data_round_2, by = "workerID", all = TRUE)
nrow(Data_round_1)
nrow(Data_round_2)
nrow(Round_1_2_merged)
head(Round_1_2_merged)

Round_1_2_merged <- Round_1_2_merged[-1, ]

(common_cols <- intersect(colnames(Data_round_1)[!colnames(Data_round_1) %in% "workerID"], 
                          colnames(Data_round_2)[!colnames(Data_round_2) %in% "workerID"]))

for (col in common_cols) {
  Round_1_2_merged[[col]] <- ifelse(!is.na(Round_1_2_merged[[paste0(col, ".x")]]),
                                    Round_1_2_merged[[paste0(col, ".x")]],
                                    Round_1_2_merged[[paste0(col, ".y")]])
  # Remove original columns
  Round_1_2_merged <- Round_1_2_merged[, -c(which(colnames(Round_1_2_merged) == paste0(col, ".x")),
                                            which(colnames(Round_1_2_merged) == paste0(col, ".y")))]
}

colnames(Round_1_2_merged)

##### round 3 #####
Round_1_2_3_merged <- merge(Round_1_2_merged, Data_round_3, by = "workerID", all = TRUE)
nrow(Round_1_2_3_merged)
nrow(Round_1_2_merged)

head(Round_1_2_3_merged)

Round_1_2_3_merged <- Round_1_2_3_merged[-1, ]

(common_cols <- intersect(colnames(Round_1_2_merged)[!colnames(Round_1_2_merged) %in% "workerID"], 
                          colnames(Data_round_3)[!colnames(Data_round_3) %in% "workerID"]))

for (col in common_cols) {
  Round_1_2_3_merged[[col]] <- ifelse(!is.na(Round_1_2_3_merged[[paste0(col, ".x")]]),
                                      Round_1_2_3_merged[[paste0(col, ".x")]],
                                      Round_1_2_3_merged[[paste0(col, ".y")]])
  
  Round_1_2_3_merged <- Round_1_2_3_merged[, -c(which(colnames(Round_1_2_3_merged) == paste0(col, ".x")),
                                                which(colnames(Round_1_2_3_merged) == paste0(col, ".y")))]
}

##### round 4 ####
Round_1_2_3_4_merged <- merge(Round_1_2_3_merged, Data_round_4, by = "workerID", all = TRUE)
nrow(Data_round_4)
nrow(Round_1_2_3_merged)
nrow(Round_1_2_3_4_merged)

Round_1_2_3_4_merged <- Round_1_2_3_4_merged[-1, ]

(common_cols <- intersect(colnames(Round_1_2_3_merged)[!colnames(Round_1_2_3_merged) %in% "workerID"], 
                          colnames(Data_round_4)[!colnames(Data_round_4) %in% "workerID"]))

for (col in common_cols) {
  Round_1_2_3_4_merged[[col]] <- ifelse(!is.na(Round_1_2_3_4_merged[[paste0(col, ".x")]]),
                                        Round_1_2_3_4_merged[[paste0(col, ".x")]],
                                        Round_1_2_3_4_merged[[paste0(col, ".y")]])

  Round_1_2_3_4_merged <- Round_1_2_3_4_merged[, -c(which(colnames(Round_1_2_3_4_merged) == paste0(col, ".x")),
                                                    which(colnames(Round_1_2_3_4_merged) == paste0(col, ".y")))]
}

colnames(Round_1_2_3_4_merged)

##### round 5 #####
Round_1_2_3_4_5_merged <- merge(Round_1_2_3_4_merged, Data_round_5, by = "workerID", all = TRUE)
nrow(Data_round_5)
nrow(Round_1_2_3_merged)
nrow(Round_1_2_3_4_5_merged)

Round_1_2_3_4_5_merged <- Round_1_2_3_4_5_merged[-1, ]

(common_cols <- intersect(colnames(Round_1_2_3_4_merged)[!colnames(Round_1_2_3_4_merged) %in% "workerID"], 
                          colnames(Data_round_5)[!colnames(Data_round_5) %in% "workerID"]))

for (col in common_cols) {
  Round_1_2_3_4_5_merged[[col]] <- ifelse(!is.na(Round_1_2_3_4_5_merged[[paste0(col, ".x")]]),
                                          Round_1_2_3_4_5_merged[[paste0(col, ".x")]],
                                          Round_1_2_3_4_5_merged[[paste0(col, ".y")]])

  Round_1_2_3_4_5_merged <- Round_1_2_3_4_5_merged[, -c(which(colnames(Round_1_2_3_4_5_merged) == paste0(col, ".x")),
                                                        which(colnames(Round_1_2_3_4_5_merged) == paste0(col, ".y")))]
}


##### round 6 #####
Round_1_2_3_4_5_6_merged <- merge(Round_1_2_3_4_5_merged, Data_round_6, by = "workerID", all = TRUE)
nrow(Data_round_6)
nrow(Round_1_2_3_merged)
nrow(Round_1_2_3_4_5_6_merged)

Round_1_2_3_4_5_6_merged <- Round_1_2_3_4_5_6_merged[-1, ]

(common_cols <- intersect(colnames(Round_1_2_3_4_5_merged)[!colnames(Round_1_2_3_4_5_merged) %in% "workerID"], 
                          colnames(Data_round_6)[!colnames(Data_round_6) %in% "workerID"]))

for (col in common_cols) {
  Round_1_2_3_4_5_6_merged[[col]] <- ifelse(!is.na(Round_1_2_3_4_5_6_merged[[paste0(col, ".x")]]),
                                            Round_1_2_3_4_5_6_merged[[paste0(col, ".x")]],
                                            Round_1_2_3_4_5_6_merged[[paste0(col, ".y")]])
  
  Round_1_2_3_4_5_6_merged <- Round_1_2_3_4_5_6_merged[, -c(which(colnames(Round_1_2_3_4_5_6_merged) == paste0(col, ".x")),
                                                            which(colnames(Round_1_2_3_4_5_6_merged) == paste0(col, ".y")))]
}

Round_1_2_3_4_5_6_merged <- Round_1_2_3_4_5_6_merged %>%
  rename_with(~ paste0(., "_T1"), -c(workerID))

# remove averages that only round 1 had
Round_1_2_3_4_5_6_merged <- Round_1_2_3_4_5_6_merged[, !colnames(Round_1_2_3_4_5_6_merged) 
                                                     %in% c("X_T1", "X.1_T1", "X.2_T1", "X.3_T1", "Raw_T1")]

# file_path <- file.path("Created_datasets")
# dir.create(file_path)
filetype <- ".csv"
name <- paste0("Raw_merged_")
filename <- paste(name, Sys.Date(), filetype, sep = '')
full_filename <- file.path(file_path, filename)
write.csv(Round_1_2_3_4_5_6_merged, file = full_filename, row.names = FALSE)
```

```{r Qualitative merging}
# First, in EXCEL, make a function to extract URLs from hyperlinked text. 

# Function URL(Hyperlink As Range)
#  URL = Hyperlink.Hyperlinks(1).Address
# End Function

# Make new clumns with linked text (folder, transcript, etc.). Then come back to this R file, and import the formatted version:
qual_tracker <- read.csv("Raw_data/NLP_recordings_tracker_SG_formatted.csv")

# rename workerID column to be consistent with quant data
qual_tracker <- qual_tracker %>%
  dplyr::rename(
    workerID = WorkerID..anonymous.)

# Remove extra last 6 columns
qual_tracker <- qual_tracker %>%
  select(-((ncol(.)-5):ncol(.)))

# Cut out extra rows
qual_tracker <- qual_tracker[1:170, ]

nrow(qual_tracker)
View(qual_tracker)

# Now, use LEFT JOIN, so all particpiants on the qual tracker are matched (but not the opposite)
qual_quant_merged <- left_join(qual_tracker, Round_1_2_3_4_5_6_merged, by = "workerID")
nrow(qual_quant_merged)
head(qual_quant_merged)

filetype <- ".csv"
name <- paste0("Raw_recordings_assessment_data_")
filename <- paste(name, Sys.Date(), filetype, sep = '')
full_filename <- file.path(file_path, filename)
write.csv(qual_quant_merged, file = full_filename, row.names = FALSE)
```

```{r Misc. coding}

# Import data if not loaded from above:
Merged_data <- read.csv("Created_datasets/Raw_recordings_assessment_data_2024-06-18.csv")

colnames(Merged_data)

#### Recovery Evaluation and Suicide Support Tool ####

Merged_data <- Merged_data %>%
  mutate(across(starts_with("Recovery.scale"), 
                ~ recode(., 
                         "Does not describe me" = 1, 
                         "Describes me slightly well" = 2, 
                         "Describes me moderately well" = 3, 
                         "Describes me very well" = 4, 
                         "Describes me extremely well" = 5, 
                         .default = as.numeric(.)), 
                .names = "{.col}_recode")) # creating new columns with recoded values 

# RESST subscales and total scores
Merged_data <- Merged_data %>%
  mutate(
    RESST_self_worth = rowMeans(select(., 
                                       c("Recovery.scale_1_T1_recode", "Recovery.scale_2_T1_recode",
                                         "Recovery.scale_3_T1_recode", "Recovery.scale_4_T1_recode",
                                         "Recovery.scale_5_T1_recode", "Recovery.scale_6_T1_recode",
                                         "Recovery.scale_7_T1_recode")), na.rm = FALSE),
    RESST_life_worth = rowMeans(select(., 
                                       c("Recovery.scale_8_T1_recode", "Recovery.scale_9_T1_recode",
                                         "Recovery.scale_10_T1_recode", "Recovery.scale_11_T1_recode")), na.rm = FALSE),
    RESST_social_worth = rowMeans(select(., 
                                          c("Recovery.scale_12_T1_recode", "Recovery.scale_13_T1_recode",
                                            "Recovery.scale_14_T1_recode", "Recovery.scale_15_T1_recode",
                                            "Recovery.scale_16_T1_recode", "Recovery.scale_17_T1_recode")), na.rm = FALSE),
    RESST_self_understanding = rowMeans(select(., 
                                                c("Recovery.scale_18_T1_recode", "Recovery.scale_19_T1_recode",
                                                  "Recovery.scale_20_T1_recode", "Recovery.scale_21_T1_recode")), na.rm = FALSE),
    RESST_all = rowMeans(select(., 
                                  c("Recovery.scale_1_T1_recode", "Recovery.scale_2_T1_recode",
                                    "Recovery.scale_3_T1_recode", "Recovery.scale_4_T1_recode",
                                    "Recovery.scale_5_T1_recode", "Recovery.scale_6_T1_recode",
                                    "Recovery.scale_7_T1_recode", "Recovery.scale_8_T1_recode",
                                    "Recovery.scale_9_T1_recode", "Recovery.scale_10_T1_recode",
                                    "Recovery.scale_11_T1_recode", "Recovery.scale_12_T1_recode",
                                    "Recovery.scale_13_T1_recode", "Recovery.scale_14_T1_recode",
                                    "Recovery.scale_15_T1_recode", "Recovery.scale_16_T1_recode",
                                    "Recovery.scale_17_T1_recode", "Recovery.scale_18_T1_recode",
                                    "Recovery.scale_19_T1_recode", "Recovery.scale_20_T1_recode",
                                    "Recovery.scale_21_T1_recode")), na.rm = FALSE)
  )

#### Satisfaction with Life Scale ####

# the scale has 7 options: Strongly agree (7), agree (6), slightly agree (5), neither agree nor disagree (4), slightly disagree (3), disagree (2), strongly disagree (1). However, here it was administered with 5. 

Merged_data <- Merged_data %>%
  mutate(across(all_of(paste0("SWLS_", 1:5, "_T1")), 
                ~ recode(trimws(.), 
                         "Strongly agree" = 5, 
                         "Somewhat agree" = 4, 
                         "Neither agree nor disagree" = 3, 
                         "Somewhat disagree" = 2, 
                         "Strongly disagree" = 1, 
                         .default = as.numeric(.)), 
                .names = "{.col}_recode"))

# total score
Merged_data <- Merged_data %>%
  mutate(
    SWLS_total = rowSums(select(., 
                                 c("SWLS_1_T1_recode", "SWLS_2_T1_recode", "SWLS_3_T1_recode", "SWLS_4_T1_recode", "SWLS_5_T1_recode")), 
                          na.rm = FALSE))

#### Suicidal Behaviors Questionnaire-Revised ####
Merged_data <- Merged_data %>%
  mutate(SBQR.2_T1_recode = case_when( # item one
    trimws(SBQR.2_T1) == "Never" ~ "1",
    trimws(SBQR.2_T1) == "It was just a brief passing thought" ~ "2",
    trimws(SBQR.2_T1) == "I have had a plan to kill myself at least once but did not try to do it" ~ "3",
                          # the original wording is "at least once to kill myself" - slightly different here
    trimws(SBQR.2_T1) == "I have had a plan at least once to kill myself and really wanted to die" ~ "4",
    trimws(SBQR.2_T1) == "I have attempted to kill myself but did not want to die" ~ "5",
    trimws(SBQR.2_T1) == "I have attempted to kill myself, and really hoped to die" ~ "6",
    TRUE ~ as.character(SBQR.2_T1)  # keep other values unchanged
  ))

# score item 1 in line with SBQ-R scoring
Merged_data <- Merged_data %>%
  mutate(
    SBQR.2_T1_recode = as.numeric(SBQR.2_T1_recode),  
    SBQR.2_T1_recode_score = case_when(
      SBQR.2_T1_recode %in% c(3, 4) ~ 3,
      SBQR.2_T1_recode %in% c(5, 6) ~ 4, 
      TRUE ~ SBQR.2_T1_recode  # Keep other values unchanged so 1 = 1 and 2 = 2 in line with SBQ-R scoring
    )
  )

Merged_data <- Merged_data %>%
  mutate(SBQR.4_T1_recode = case_when( # item two
    trimws(SBQR.4_T1) == "Never" ~ "1",
    trimws(SBQR.4_T1) == "Rarely (1 time)" ~ "2",
    trimws(SBQR.4_T1) == "Sometimes (2 times)" ~ "3",
    trimws(SBQR.4_T1) == "Often (3-4 times)" ~ "4",
    trimws(SBQR.4_T1) == "Very Often (5 or more times)" ~ "5",
    TRUE ~ as.character(SBQR.4_T1)  
  ))

table(Merged_data$SBQR.5_T1)
Merged_data <- Merged_data %>%
  mutate(SBQR.5_T1_recode = case_when( # item three
    trimws(SBQR.5_T1) == "No" ~ "1",
    trimws(SBQR.5_T1) == "Yes, at one time, but did not really want to do it" ~ "2", # should be "want to die", not "do it"
    trimws(SBQR.5_T1) == "Yes, at one time, and really wanted to die" ~ "3",
    trimws(SBQR.5_T1) == "Yes, more than once, but did not want to do it" ~ "4",
    trimws(SBQR.5_T1) == "Yes, more than once, and really wanted to do it" ~ "5",
    TRUE ~ as.character(SBQR.5_T1)  
  ))

# score item 3 in line with SBQ-R scoring
Merged_data <- Merged_data %>%
  mutate(
    SBQR.5_T1_recode = as.numeric(SBQR.5_T1_recode),  
    SBQR.5_T1_recode_score = case_when(
      SBQR.5_T1_recode %in% c(2, 3) ~ 2,
      SBQR.5_T1_recode %in% c(4, 5) ~ 3, 
      TRUE ~ SBQR.5_T1_recode # Keep other values unchanged so 1 = 1 in line with SBQ-R scoring
    )
  )

Merged_data <- Merged_data %>%
  mutate(SBQR.6_T1_recode = case_when( # item four
    trimws(SBQR.6_T1) == "Never" ~ "0",
    trimws(SBQR.6_T1) == "No chance at all" ~ "1",
    trimws(SBQR.6_T1) == "Rather Unlikely" ~ "2",
    trimws(SBQR.6_T1) == "Unlikely" ~ "3",
    trimws(SBQR.6_T1) == "Likely" ~ "4",
    trimws(SBQR.6_T1) == "Rather Likely" ~ "5",
        trimws(SBQR.6_T1) == "Very Likely" ~ "6",
    TRUE ~ as.character(SBQR.6_T1)  
  ))

# SBQ-R total score
Merged_data <- Merged_data %>%
  mutate(
    SBQR.2_T1_recode_score = as.numeric(SBQR.2_T1_recode_score),
    SBQR.4_T1_recode = as.numeric(SBQR.4_T1_recode),
    SBQR.5_T1_recode_score = as.numeric(SBQR.5_T1_recode_score),
    SBQR.6_T1_recode = as.numeric(SBQR.6_T1_recode)
  ) %>%
  mutate(
    SBQR_total = rowSums(select(., c(SBQR.2_T1_recode_score, # recoded item 1
                                     SBQR.4_T1_recode,       # item 2
                                     SBQR.5_T1_recode_score, # recoded item 3
                                     SBQR.6_T1_recode)),     # recoded item 4
                         na.rm = FALSE)
  )
   
summary(Merged_data$SBQR_total)

#### Future self Continuity Questionnaire ####

# Similarity items
Merged_data <- Merged_data %>%
  mutate(
    across(
      FSCQ.1_T1:FSCQ.4_T1,
      as.character
    )
  ) %>%
  mutate(
    across(
      FSCQ.1_T1:FSCQ.4_T1,
      ~ case_when(
        trimws(.) == "Completely different" ~ "1",
        trimws(.) == "Somewhat different" ~ "2",
        trimws(.) == "A little different" ~ "3",
        trimws(.) == "Similar" ~ "4",
        trimws(.) == "Very similar" ~ "5",
        trimws(.) == "Exactly the same" ~ "6",
        TRUE ~ as.character(.)
      ),
      .names = "{.col}_recode"
    )
  )

# Vividness and Positive items
Merged_data <- Merged_data %>%
  mutate(
    across(
      FSCQ.5_T1:FSCQ.10_T1,
      as.character
    )
  ) %>%
  mutate(
    across(
      FSCQ.5_T1:FSCQ.10_T1,
      ~ case_when(
        trimws(.) == "Not at all" ~ "1",
        trimws(.) == "Not very well" ~ "2",
        trimws(.) == "Somewhat" ~ "3",
        trimws(.) == "Pretty well" ~ "4",
        trimws(.) == "Very Strongly" ~ "5",
        trimws(.) == "Very strongly" ~ "5", # some surveys had different cases
        trimws(.) == "Perfectly" ~ "6",
        TRUE ~ as.character(.)
      ),
      .names = "{.col}_recode"
    )
  ) %>%
  mutate(
    across(
      matches("^FSCQ\\.[1-9]|10_T1$"),  
      ~ na_if(., "")  
    )
  )
```

